export const segments = [
  {
    id: "01-sign-in",
    startCue: "open-sign-in",
    endCue: "open-knowledge",
    signedIn: false,
    openAt: "/sign-in",
    waitFor: "#email",
  },
  {
    id: "02-your-papers",
    startCue: "open-knowledge",
    endCue: "open-report",
    signedIn: true,
    openAt: "/knowledge",
    waitFor: "a[href^='/knowledge/']",
  },
  {
    id: "03-report-sections",
    startCue: "open-report",
    endCue: "open-citations",
    signedIn: true,
    openAt: "/reports",
    waitFor: "a[href^='/reports/']",
  },
  {
    id: "04-failed-citation",
    startCue: "open-citations",
    endCue: "start-project",
    signedIn: true,
    openAt: null,
    waitFor: null,
  },
  {
    id: "05-the-project",
    startCue: "start-project",
    endCue: "show-proposals",
    signedIn: true,
    openAt: "/projects",
    waitFor: "a[href^='/projects/']",
  },
  {
    id: "06-prior-art",
    startCue: "show-proposals",
    endCue: "open-draft",
    signedIn: true,
    openAt: null,
    waitFor: null,
  },
  {
    id: "07-the-draft",
    startCue: "open-draft",
    endCue: "end-demo",
    signedIn: true,
    openAt: null,
    waitFor: null,
  },
];
